//
// ex: set ro:
// DO NOT EDIT.
// generated by smc (http://smc.sourceforge.net/)
// from file : automat_sm.sm
//

#include "GameProvess.hpp"
#include "GameProvess_sm.h"

using namespace statemap;

// Static class declarations.
GameMap_NotStarted GameMap::NotStarted("GameMap::NotStarted", 0);
GameMap_MainMenu GameMap::MainMenu("GameMap::MainMenu", 1);
GameMap_Playing GameMap::Playing("GameMap::Playing", 2);
GameMap_GameOver GameMap::GameOver("GameMap::GameOver", 3);

void gameProcessState::Default(GameProvess_sm& context)
{
    throw (
        TransitionUndefinedException(
            (context.getState()).getName(),
            context.getTransition()));

}

//
// Local variables:
//  buffer-read-only: t
// End:
//
